### PR TITLE
Added few words

### PR DESCRIPTION
**Pull request by MissingBytes**

### CODE REVIEW

**Comment by unhammer** [comment]
Don't add generated files, please. The only file that should be in your commit is apertium-kan.kan.dix
(your commit has Makefile.in, missing, config.log kan.autogen.bin etc.)

**Comment by sushain97** [comment]
@unhammer sounds like we need some gitignore magic in all the repos?

**Comment by unhammer** [comment]
that would probably help … are people being taught to do `git add -A` or something?

**Comment by sushain97** [comment]
Not sure...

**Pull request merged**
